### ISSUE TITLE
Use in included hook of addon

### ISSUE THREAD

**Issue by patocallaghan** [kellyselden/ember-cli-node-modules-to-vendor#57]
sorry if opening an issue is the wrong thing, but is it possible to use this addon in the `included` hook of another addon?

All examples show using the `ember-cli-build.js` but an addon entry point is an `index.js`.

**Comment by patocallaghan** [comment]
For additional context I've tried the two following approaches without much success:

```
module.exports = {
  name: 'my-addon',
  options: {
    nodeModulesToVendor: [
      new Funnel('node_modules/blueimp-canvas-to-blob/js', {
        destDir: 'blueimp-canvas-to-blob',
        files: ['canvas-to-blob.js']
      })
    ],
  },
  included: function (app) {
    this._super(app);
    app.import('vendor/addon-name/blueimp-canvas-to-blob/canvas-to-blob.js');
  }
}
```

and (which was clutching at straws a little bit)

```
module.exports = {
  name: 'my-addon',
  included: function (app) {
    this._super(app);
    app.nodeModulesToVendor = [
      new Funnel('node_modules/blueimp-canvas-to-blob/js', {
        destDir: 'blueimp-canvas-to-blob',
        files: ['canvas-to-blob.js']
      })
    ];
    app.import('vendor/blueimp-canvas-to-blob/canvas-to-blob.js');
  }
}
```

**Comment by kellyselden** [comment]
This wasn't designed for use in addons. You will probably be better off trying ember-cli-node-assets. I would support a PR to add support, but I don't really consider it a bug. Thanks for the issue.

**Comment by patocallaghan** [comment]
@kellyselden no problem, that's what I ended up doing, just using `ember-cli-node-assets` instead.
