### ISSUE TITLE
README has improper syntax to check environment

### ISSUE THREAD

**Issue by vkoves** [kellyselden/ember-cli-node-modules-to-vendor#72]
It's been challenging to find the documentation for this, but the README references `EmberApp.env`, which is a function. The proper way to check the environment is `EmberApp.env() !== 'development'`, at least on Ember 2.11.1. See [the definition of env](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L434) in `ember-app.js` in ember-cli.

**Comment by kellyselden** [comment]
Good call. I was confusing it with `app.env`.

**Comment by kellyselden** [comment]
fixed
