### ISSUE TITLE
Is still useful this plugin with ember-cli 2.15 "app.import" from node_modules?

### ISSUE THREAD

**Issue by johnunclesam** [kellyselden/ember-cli-node-modules-to-vendor#79]
Is still useful this plugin with ember-cli 2.15 "app.import" from node_modules?

https://emberjs.com/blog/2017/09/01/ember-2-15-released.html#toc_app-import-files-within-node_modules

**Comment by kellyselden** [comment]
nope, this is now only useful for pre 2.15 apps. Feel free to add deprecation warning.
