### ISSUE TITLE
App fails to build when .npmignore is present in imported folder

### ISSUE THREAD

**Issue by Ravenstine** [kellyselden/ember-cli-node-modules-to-vendor#88]
I'm trying to import this folder from the pre-release of Materialize 1.0.0:

https://github.com/Dogfalo/materialize/tree/1.0.0-alpha.1/js

The fact that there is a .npmignore file seems to be a problem:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor)] failed with:
Error: Merge error: file .npmignore exists in /Users/ravenstine/workspace/fire-marshall/tmp/broccoli_merge_trees-input_base_path-OjP5j24K.tmp/0 and /Users/ravenstine/workspace/fire-marshall/tmp/broccoli_merge_trees-input_base_path-OjP5j24K.tmp/1
```

Deleting that file makes the problem go away, but someone building my app shouldn't have to delete a file first before running.  Importing from one directory level up also works, but obviously isn't ideal.

**Comment by kellyselden** [comment]
Hmm I'm not sure if this is an issue with my code or with broccoli.

**Comment by Ravenstine** [comment]
I was able to work around with this:

```javascript
    nodeModulesToVendor: [
      new Funnel(new UnwatchedDir('node_modules/materialize-css/js'), {
        destDir: 'materialize-css',
        files: ['*.js']
      })
    ]
```

So I guess the answer is that it's more an issue with Broccoli in the sense I'm making a tree with files it doesn't support.(unless there's some nuance to .npmignore files in particular i don't know about)  Creating the funnel seems to be the right answer.

**Comment by kellyselden** [comment]
Thanks for the info.
